apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: flat-variables
  title: Flat Variable
  description: A template to test the error time out
spec:
  owner: Deepesh.kumar
  type: service
  parameters:
    - title: Email Content
      required:
        - username
        - stages.DummyStage.variables.Stage1Variable
        - stages.TempStage.variables.demo
        - stages.TempStage.variables.demotwo
      properties:
        username:
          title: Write the Content for your Email
          type: string
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        stages.DummyStage.variables.Stage1Variable:
          title: Stage1Variable
          type: string
        stages.TempStage.variables.demo:
          title: demo
          type: string
        stages.TempStage.variables.demotwo:
          title: demotwo
          type: string
  steps:
    - id: trigger
      name: Writing the email body
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/idp-admin/orgs/default/projects/idpprojectsc/pipelines/DummyPipeline/pipeline-studio/?storeType=INLINE&stageId=DummyStage&sectionId=EXECUTION
        inputset: 
          username: ${{ parameters.username }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
