pipeline:
  name: remote pipeline with remote stage template
  identifier: remote_pipeline_with_remote_stage_template
  projectIdentifier: Deepesh_CDE
  orgIdentifier: IDP
  tags: {}
  stages:
    - stage:
        name: Cust Acc
        identifier: Cust_Acc
        tags: {}
        template:
          templateRef: account.IDP_Custom
          gitBranch: dev
