pipeline:
  name: remote pipeline with remote stage template
  identifier: remote_pipeline_with_remote_stage_template
  projectIdentifier: Deepesh_CDE
  orgIdentifier: IDP
  tags: {}
  stages:
    - stage:
        name: Cust Acc
        identifier: Cust_Acc
        tags: {}
        template:
          templateRef: account.IDP_Custom
          gitBranch: dev
    - stage:
        name: RemoteStageTemp
        identifier: RemoteStageTemp
        tags: {}
        template:
          templateRef: RemoteStagetemplate
          gitBranch: dev
          templateInputs:
            type: Custom
            variables:
              - name: demo
                type: String
                value: <+input>
    - stage:
        name: Custom One
        identifier: Custom_One
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'Hello'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
